{
    "name": "McCrae World Nicol",
    "page": "kitten02.html",
    "src": "img/kittens/nicol.jpg",
    "price": "70000",
    "decription": "Люблю какать в тапки",
    "daddy":"sireBoy01",
    "mammy":"sireGirl01",
    "sex": "кошка",
    "breed": "SCS (скоттиш-страйт)",
    "color": "black golden (ny 12)",
    "bdate": "26.10.19",
    "photos" :["img/kittens/nicol/nicol1.jpg","img/kittens/nicol/nicol2.jpg","img/kittens/nicol/nicol3.jpg"],
    "photosmini" :["img/kittens/nicol/small/nicol1.jpg","img/kittens/nicol/small/nicol2.jpg","img/kittens/nicol/small/nicol3.jpg"],
    "status":"Забронирован"
},
{
    "name": "McCrae World Nemo",
    "page": "kitten04.html",
    "src": "img/kittens/nemonew.jpg",
    "price": "50000",
    "decription": "Просто няша",
    "daddy":"sireBoy01",
    "mammy":"sireGirl01",
    "sex": "кот",
    "breed": "SCS (скоттиш-страйт)",
    "color": "black golden (ny 12)",
    "bdate": "26.10.19",
    "photos" :["img/kittens/nemo/nemo1.jpg","img/kittens/nemo/nemo2.jpg","img/kittens/nemo/nemo3.jpg",
    "img/kittens/nemo/nemo4.jpg", "img/kittens/nemo/nemo5.jpg"],
    "photosmini" :["img/kittens/nemo/small/nemo1.jpg","img/kittens/nemo/small/nemo2.jpg","img/kittens/nemo/small/nemo3.jpg",
    "img/kittens/nemo/small/nemo4.jpg", "img/kittens/nemo/small/nemo5.jpg"],
    "status":"Забронирован"
    
},